In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [3]:
df.head()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,Acura,Integra,Small,12.9,15.9,18.8,25.0,31.0,NaN,Front,...,5.0,177.0,102.0,68.0,37.0,26.5,NaN,2705.0,non-USA,Acura Integra
1,NaN,Legend,Midsize,29.2,33.9,38.7,18.0,25.0,Driver & Passenger,Front,...,5.0,195.0,115.0,71.0,38.0,30.0,15.0,3560.0,non-USA,Acura Legend
2,Audi,90,Compact,25.9,29.1,32.3,20.0,26.0,Driver only,Front,...,5.0,180.0,102.0,67.0,37.0,28.0,14.0,3375.0,non-USA,Audi 90
3,Audi,100,Midsize,NaN,37.7,44.6,19.0,26.0,Driver & Passenger,NaN,...,6.0,193.0,106.0,NaN,37.0,31.0,17.0,3405.0,non-USA,Audi 100
4,BMW,535i,Midsize,NaN,30.0,NaN,22.0,30.0,NaN,Rear,...,4.0,186.0,109.0,69.0,39.0,27.0,13.0,3640.0,non-USA,BMW 535i

In [4]:
df.shape

(93, 27)

In [5]:
df.info

<bound method DataFrame.info of    Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0
2          Audi       90  Compact       25.9   29.1       32.3      20.0
3          Audi      100  Midsize        NaN   37.7       44.6      19.0
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0
..          ...      ...      ...        ...    ...        ...       ...
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0
91        Volvo      240  Compact       21.8   22.7       23.5      21.0
92          NaN      850  Midsize       24.8   26.7       28.5      20.0

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0
1          25.0  Driver & Passenger      Front  ...        5.0   195.0
2          26.0         Driver only      Front  ...        5.0   180.0
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0
4          30.0                 NaN       Rear  ...        4.0   186.0
..          ...                 ...        ...  ...        ...     ...
88         21.0                 NaN      Front  ...        7.0   187.0
89         30.0                 NaN      Front  ...        5.0   180.0
90         25.0                 NaN      Front  ...        4.0   159.0
91         28.0         Driver only       Rear  ...        5.0   190.0
92         28.0  Driver & Passenger      Front  ...        5.0   184.0

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0
1       115.0   71.0         38.0           30.0          15.0  3560.0
2       102.0   67.0         37.0           28.0          14.0  3375.0
3       106.0    NaN         37.0           31.0          17.0  3405.0
4       109.0   69.0         39.0           27.0          13.0  3640.0
..        ...    ...          ...            ...           ...     ...
88      115.0   72.0         38.0           34.0           NaN  3960.0
89      103.0   67.0         35.0           31.5          14.0  2985.0
90       97.0   66.0         36.0           26.0          15.0  2810.0
91      104.0   67.0         37.0           29.5          14.0  2985.0
92      105.0   69.0         38.0           30.0          15.0  3245.0

     Origin                Make
0   non-USA       Acura Integra
1   non-USA        Acura Legend
2   non-USA             Audi 90
3   non-USA            Audi 100
4   non-USA            BMW 535i
..      ...                 ...
88      NaN  Volkswagen Eurovan
89  non-USA   Volkswagen Passat
90  non-USA  Volkswagen Corrado
91  non-USA           Volvo 240
92  non-USA           Volvo 850

[93 rows x 27 columns]>

In [14]:
result = df.loc[df.index[::20], ['Manufacturer', 'Model', 'Type']]

In [16]:
print(result)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [17]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [18]:
df.head()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,Acura,Integra,Small,12.9,15.9,18.8,25.0,31.0,NaN,Front,...,5.0,177.0,102.0,68.0,37.0,26.5,NaN,2705.0,non-USA,Acura Integra
1,NaN,Legend,Midsize,29.2,33.9,38.7,18.0,25.0,Driver & Passenger,Front,...,5.0,195.0,115.0,71.0,38.0,30.0,15.0,3560.0,non-USA,Acura Legend
2,Audi,90,Compact,25.9,29.1,32.3,20.0,26.0,Driver only,Front,...,5.0,180.0,102.0,67.0,37.0,28.0,14.0,3375.0,non-USA,Audi 90
3,Audi,100,Midsize,NaN,37.7,44.6,19.0,26.0,Driver & Passenger,NaN,...,6.0,193.0,106.0,NaN,37.0,31.0,17.0,3405.0,non-USA,Audi 100
4,BMW,535i,Midsize,NaN,30.0,NaN,22.0,30.0,NaN,Rear,...,4.0,186.0,109.0,69.0,39.0,27.0,13.0,3640.0,non-USA,BMW 535i

In [19]:
df['Min.Price'] = df['Min.Price'].apply(lambda x: df['Min.Price'].mean() if pd.isnull(x) else x)

In [20]:
df['Max.Price'] = df['Max.Price'].apply(lambda x: df['Max.Price'].mean() if pd.isnull(x) else x)

print(df[['Min.Price', 'Max.Price']])

    Min.Price  Max.Price
0   12.900000  18.800000
1   29.200000  38.700000
2   25.900000  32.300000
3   17.118605  44.600000
4   17.118605  21.459091
..        ...        ...
88  16.600000  22.700000
89  17.600000  22.400000
90  22.900000  23.700000
91  21.800000  23.500000
92  24.800000  28.500000

[93 rows x 2 columns]

import numpy as np

# Create a DataFrame
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))


# Get the rows with row sum greater than 100
result = df[df.sum(axis=1) > 100]

print(result)

In [21]:
import pandas as pd
import numpy as np

# Create a DataFrame
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Get the rows with row sum greater than 100
result = df[df.sum(axis=1) > 100]

print(result)

     0   1   2   3
1   31  36  26  32
6   20  12  34  35
7   38  35  28  13
8   39  10  25  33
9   37  35  36  23
10  30  37  35  36
14  33  20  38  23

In [22]:
# Create a 4x4 NumPy array filled with random integers between 1 and 100
arr = np.random.randint(1, 101, (4, 4))

# Reshape the array into two separate 2D arrays for rows and columns
rows = arr.reshape(2, 8)
cols = arr.T.reshape(2, 8)

# Define a lambda function to calculate the sum of each row and column
sum_row = lambda x: np.sum(x, axis=1)
sum_col = lambda x: np.sum(x, axis=1)

# Calculate the sum of each row and column using the lambda function
sum_rows_array = sum_row(rows)
sum_cols_array = sum_col(cols)

print("Rows:")
print(rows)
print("Sum of rows:")
print(sum_rows_array)
print("\nColumns:")
print(cols)
print("Sum of columns:")
print(sum_cols_array)

Rows:
[[93 22 15 36 32 42 90 96]
 [13 38 76 48 32 74 19 49]]
Sum of rows:
[426 349]

Columns:
[[93 32 13 32 22 42 38 74]
 [15 90 76 19 36 96 48 49]]
Sum of columns:
[346 429]